---

sudo: false

language: node_js

matrix:
    fast_finish: true
    allow_failures:
        - node_js: "5"

node_js:
    - "0.10"
    - "0.12"
    - "4"
    - "5"

services:
    - couchdb

env:
    global:
        - NODE_ENV=test
        - APPLICATION_PERSISTENT_DIRECTORY=$HOME

before_install:
    - npm config set ca ""

before_script:
    - npm run build

script:
    - npm run lint
    - npm run test
