language: node_js
node_js:
    - "0.10"
    - "0.8"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
before_install:
    - git clone git://github.com/mycozycloud/cozy-data-indexer.git
    - cd cozy-data-indexer
    - python server.py
    - sleep 3
    - curl http://localhost:9102/
    - cd ..
