language: node_js
matrix:
    fast_finish: true
    allow_failures:
        - node_js: "0.12"
node_js:
    - "0.12"
    - "0.10"
    - "4"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
before_install:
    - npm config set ca ""
    - npm install coffee-script -g
